version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./tfc.sql:/docker-entrypoint-initdb.d/init.sql # prepopulate database
       - db_data:/var/lib/mysql # persist database data inside docker storage
     restart: always
     env_file:
      - .env
     environment:
      DOCKER_COMPOSE_YML_LOCATION: ${PWD}
     container_name: wp_db

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - "9000:80"
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       DOCKER_COMPOSE_YML_LOCATION: ${PWD}
     container_name: wp_phpmyadmin

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
       DOCKER_COMPOSE_YML_LOCATION: ${PWD}
     volumes:
       - ./wp-content:/var/www/html/wp-content
     container_name: wp_wordpress
volumes:
    db_data: {}
